env:
  global:
      # DOCKER_USER
      - secure: "WiD9hQivDhQ8RnF6Q/KnnL5P8kENh7lPAmjqtL7dtTxi3vZ1sXCRH5Wh2m/3C0Gph5WQjYpX17YKvzapfBwGvxbH0lvaSTkZj33Omiog3pa6UUO71bjVoEde0X598wJ4JBmVCXVN0R0nOAo7xfjU5MG2jZFyyGqVP+o4l6pFqfujbSwaAZARrlWYJXuGHhWtcYYWt2cQKo8018c9I74kLLOY9jElPDiFrgLRGLG7AKd/8T3ogFVQs4dfwxp3ldej2MK31SgEASqDYECAv9HSpkcZxUIuTO6Smai2m3qioddUalyHJsZsXmxsNc7WPg8AOhA35fiEy1/SQRf+runyahuQ3J1UNUoZmPPuo861xJ+Gzl6qSh+bs+G8ujFZ59soXyhs153HbAwATEKbK6AzIy2GEUVTgGg10I0iYpKVbbjJQtv/alAwqe8Q0T5ced3aNPgqz2EvkmvksSAbCV7RHNUeBE0/WIvddu9jGscede0+s1GqrMD/UcK+nRODH+I6gM+gUVjdvZ6yUZ/VygwV0HshRjJfrzpvXDNo5Mdm9UlWgiSpw/MUB60FYO9JT/DBTwe5WOXscYFqUES+rr32iD+MTyhPkkLzHkYH+/WVaCRJDXg6wjkR0jv5zbWih8We8Kdk5GXroWR2kVBKQCOElYh4rjm0DoZywqHJgbmyLm8="
      # DOCKER_PASS
      - secure: "eRluKAA8JYoN7gWMK0CWLzb9e81+6pWUttThNfuEYZo8zUBMbC38/Mk5AGmky6bUJNAsLkaxS6v6YxOD71yaB9mPo4zAGBykfkB7CxLLm10ITUgHLBLTPFqy+t0Dc+vQEe/vBVw/4I1H/TAPGOzOScVG5xvB5v0ZXjLQ+MnesK6fSmNY161SvZ7oy17yxAGOHzyVoQiLXV7NG+cMCvy7uWEj5jQ8psXGTLOWHp1LRagNuovOk1NpaJylGrvSHnaZ8Ec8GYS+4K53w1BStloNpZlf59c8ojaaB86iJVYjQ3HPCYTo3J31nIbO/HKSGQWm3tsS1NfkIwc2G11EqhYrITv/6oGhna6uE4JXXjmwFvM08SXGPyswNQ1hKw7KNkuRhbqXSwBxfBm6AUmtN2BJx+tyszwcyE5ar1KNGnZFSTu+gPmo6A4M+HoohWvcv4rqyyfI9QO2y12TB98AdFg5Brv/oOxvZqTxhR2EHzIfEuh2K15aIo+pCGC1PSndB+lSav8MFcoa7MeLF+/kcN36+ger1+8gXxcduuSJ8FnXkrUn1mlbC0c/45jqXbDXZQZkvryDSKvh/PTJu6NNBME61on5ufZr5iBpOuY4jh2Z0LRaU2RDpY43MlXzpmkL+ksGimzjYvXoIkkH8z1CZWBpEww62K8fl5pqN2ZqLoDbKms="
      - DOCKER_COMPOSE_VERSION=1.10.0
dist: trusty
sudo: required
language: python
python:
    - "3.5"
install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - curl -sSL "https://get.docker.com/gpg" |
     sudo -E apt-key add -
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" |
     sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" \
     -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version
#script:
#  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
#  - docker-compose -f docker-compose.yml -f versions.yml build --pull
#  - docker-compose -f docker-compose.yml -f versions.yml push
#  on:
#    tags: true
install:
  - echo "Do nothing"
script:
  - echo "Do nothing"
deploy:
  provider: script
  script: /bin/sh travis_deploy.sh
  on:
      branch: master