version: '2'
services:
    silkworkbench:
        image: openbudgets/silkworkbench:0.0.4
        build: ./silkworkbench
        volumes:
            - ../volumes/silkworkbench/silk:/root/.silk
        ports:
            - "9000:9000"
    alignmentmysql:
        image: openbudgets/alignmentmysql:0.0.4
        build: ./alignmentmysql
        volumes:
            - ../volumes/alignment/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=$ALIGNMENT_MYSQL_PW
        ports:
            - "3306:3306"
    alignmentredis:
        image: openbudgets/alignmentredis:0.0.4
        build: ./alignmentredis
        volumes:
            - ../volumes/alignment/redis:/data
        ports:
            - "6379:6379"
    alignmentui:
        image: openbudgets/alignmentui:0.0.4
        build: ./alignmentui
        volumes:
            - ../volumes/virtuosoStaging/data:/data
        environment:
            - MYSQL_ROOT_PASSWORD=$ALIGNMENT_MYSQL_PW
            - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
            - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
        links:
            - alignmentmysql
            - alignmentredis
    linkedpipes_fdp:
        image: openbudgets/linkedpipes:0.0.4
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
        ports:
            - "8181:8181" # Webserver & URI dereferencable URI for pipelines + templates
            - "8170:8170" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data psort
            - "8101:9101" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    sshserver:
        image: openbudgets/sshserver:0.0.4
        build: ./sshserver
        volumes:
            - ../volumes/nginx/dumps:/dumps
            - ../volumes/sshserver/log:/var/log
    virtuoso_staging:
        image: openbudgets/virtuoso_staging:0.0.4
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
            - ./virtuoso/staging/importDump.sh:/importDump.sh
            - ./virtuoso/staging/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
        environment:
            - DBA_PASSWORD=$VIRTUOSO_STAG_PW
            - SPARQL_UPDATE=true
            #- DEFAULT_GRAPH=
        ports:
            - "8890:8890"
            - "1111:1111"
    virtuoso_production:
        image: openbudgets/virtuoso_production:0.0.4
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoProduction/data:/data
            - ../volumes/virtuosoStaging/data:/newdata
            - ./virtuoso/production/startVirtuoso.sh:/startVirtuoso.sh
            - ./virtuoso/production/supervisord.conf:/etc/supervisord.conf
            - ./virtuoso/production/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
        environment:
            - DBA_PASSWORD=$VIRTUOSO_PROD_PW
            - SPARQL_UPDATE=false
            #- DEFAULT_GRAPH=te
        ports:
            - "8891:8890"
            - "1112:1111"
    triple_store_staging:
        image: openbudgets/triple_store_staging:0.0.4
        build: ./fuseki
        volumes:
            - ./fuseki/staging/start.sh:/start.sh
            - ./fuseki/staging:/staging
            - ../volumes/tripleStoreStaging/log:/var/log
            - ../volumes/tripleStoreStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
        ports:
            - "33030:3030"
            - "39001:9001" # supervisord frontend
    triple_store_production:
        image: openbudgets/triple_store_production:0.0.4
        build: ./fuseki
        volumes:
            - ./fuseki/production/start.sh:/start.sh
            - ../volumes/tripleStoreProduction/log:/var/log
            - ../volumes/tripleStoreProduction/data:/data
            - ../volumes/tripleStoreStaging/data:/newdata
        ports:
            - "43030:3030"
            - "49001:9001" # supervisord frontend
    rudolf:
        image: openbudgets/rudolf:0.0.4
        build: ./rudolf
        volumes:
            - ../volumes/rudolf/www:/var/www
        links:
            - triple_store_production
            - virtuoso_production
            - virtuoso_staging
    rdfbrowser:
        image: openbudgets/rdfbrowser:0.0.4
        build: ./rdfbrowser
        volumes:
            - ../volumes/rdfbrowser/storage/database.sqlite:/var/www/RDFBrowser/storage/database.sqlite
            - ./rdfbrowser/dev/apache2.conf:/etc/apache2/apache2.conf
        ports:
            - "8111:80"
        links:
            - virtuoso_staging
            - virtuoso_production
    dampostgres:
        image: openbudgets/dampostgres:0.0.4
        build: ./dampostgres
        volumes:
            - ../volumes/dam/dampostgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=$DAM_POSTGRES_PW
    damapp:
        image: openbudgets/damapp:0.0.4
        build: ./damapp
        ports:
            - "5000:5000"
        links:
            - dampostgres
        environment:
            - DAM_POSTGRES_PW=$DAM_POSTGRES_PW
    nginx:
        image: openbudgets/nginx:0.0.4
        build: ./nginx
        volumes:
            - ./nginx/conf/nginx_dev.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/nginx/letsencrypt/www:/tmp/letsencrypt/www # Lets encrypt files
            - ../volumes/nginx/letsencrypt/etc:/etc/letsencrypt # Lets encrypt files
            - ../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt # Lets encrypt files
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/static_files/images:/var/www/images
            - ./nginx/static_files/svg:/var/www/svg
        links:
            - linkedpipes_fdp
            - triple_store_staging
            - triple_store_production
            - virtuoso_staging
            - virtuoso_production
            - rudolf
            - os-viewer
            - os-explorer
            - os-admin
            - indigo
            - rdfbrowser
            - alignmentui
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
#        environment:
#            - NGINX_BASIC_AUTH_PW=$NGINX_BASIC_AUTH_PW
#            - NGINX_BASIC_AUTH_USER=$NGINX_BASIC_AUTH_USER
    os-viewer:   #image: openspending/os-viewer
        image: openbudgets/os-viewer:0.0.4
        build: ./os-viewer
        expose:
          - "8000"
        ports:
          - "9003:8000"
        volumes:
            - ./os-viewer/dev_config:/app/app/config
        environment:
            - DEFAULT_HOST=http://localhost
            - DEFAULT_BASE_PATH=/viewer
            - OS_EXTERNAL_ADDRESS=http://localhost
            - OS_VIEWER_API_HOST=http://localhost
            - OS_VIEWER_AUTH_HOST=http://next.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://localhost
            - OS_VIEWER_DATAMINE_HOST=http://localhost
            #- OS_VIEWER_API_COSMO_HOST
            #- OS_VIEWER_BASE_PATH
    os-explorer:
        image: openbudgets/os-explorer:0.0.4
        build: ./os-explorer
        volumes:
          - ./os-explorer/dev_themes:/app/app/scripts/services/themes
        expose:
          - "8000"
        environment:
          - WORKDIR=/apps
    os-admin:
        image: openbudgets/os-admin:0.0.4
        expose:
          - "8000"
        restart: always
    indigo:
        image: openbudgets/indigo:0.0.4
        build: ./indigo
        ports:
          - "4200:4200"
        links:
          - damapp

#    vocol:
#        build: ./vocol
#        ports:
#          - "4200:4200"






# Subnet-Size net-Mask-Size (CIDR)
# 256 24
# 128 25
# 64 26
# 32 27
# 16 28 <<<<<
# 8 29
# 4 30
# 2 31
# 1 32

    #rudolf:

    #alignmentUI:

    #fileServerDataMining:







