version: '2'
services:
    linkedpipes_fdp:
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
        ports:
            - "8181:8181" # Webserver & URI dereferencable URI for pipelines + templates
            - "8170:8170" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data psort
            - "8101:9101" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    sshserver:
        build: ./sshserver
        volumes:
            - ../volumes/nginx/dumps:/dumps
            - ../volumes/sshserver/log:/var/log
    virtuoso_staging:
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
            - ./virtuoso/staging/importDump.sh:/importDump.sh
            - ./virtuoso/staging/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
        environment:
            - DBA_PASSWORD=$VIRTUOSO_STAG_PW
            - SPARQL_UPDATE=true
            #- DEFAULT_GRAPH=
        ports:
            - "8890:8890"
            - "1111:1111"
    virtuoso_production:
        build: ./virtuoso
        volumes:
            - ../volumes/virtuosoProduction/data:/data
            - ../volumes/virtuosoStaging/data:/newdata
            - ./virtuoso/production/startVirtuoso.sh:/startVirtuoso.sh
            - ./virtuoso/production/supervisord.conf:/etc/supervisord.conf
            - ./virtuoso/production/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
        environment:
            - DBA_PASSWORD=$VIRTUOSO_PROD_PW
            - SPARQL_UPDATE=false
            #- DEFAULT_GRAPH=te
        ports:
            - "8891:8890"
            - "1112:1111"
    triple_store_staging:
        build: ./fuseki
        volumes:
            - ./fuseki/staging/start.sh:/start.sh
            - ./fuseki/staging/createGraphFiles.sh:/createGraphFiles.sh
            - ../volumes/tripleStoreStaging/log:/var/log
            - ../volumes/tripleStoreStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
        ports:
            - "33030:3030"
            - "39001:9001" # supervisord frontend
    triple_store_production:
        build: ./fuseki
        volumes:
            - ./fuseki/production/start.sh:/start.sh
            - ../volumes/tripleStoreProduction/log:/var/log
            - ../volumes/tripleStoreProduction/data:/data
            - ../volumes/tripleStoreStaging/data:/newdata
        ports:
            - "43030:3030"
            - "49001:9001" # supervisord frontend
    rudolf:
        build: ./rudolf
        volumes:
            - ../volumes/rudolf/www:/var/www
        links:
            - triple_store_production
            - virtuoso_production
            - virtuoso_staging
    rdfbrowser:
        build: ./rdfbrowser
        volumes:
            - ./rdfbrowser/database.sqlite:/var/www/RDFBrowser/storage/database.sqlite
            - ../volumes/rdfbrowser/logs:/var/www/RDFBrowser/storage/logs
        ports:
            - "8111:80"
        links:
            - virtuoso_staging
            - virtuoso_production
    dam:
        build: ./dam
        volumes:
            - ../volumes/dam/app:/DAM
        ports:
            - "5100:5000"
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/nginx/letsencrypt/www:/tmp/letsencrypt/www # Lets encrypt files
            - ../volumes/nginx/letsencrypt/etc:/etc/letsencrypt # Lets encrypt files
            - ../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt # Lets encrypt files
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/images:/var/www/images
            - ./nginx/svg:/var/www/svg
        links:
            - linkedpipes_fdp
            - triple_store_staging
            - triple_store_production
            - virtuoso_staging
            - virtuoso_production
            - rudolf
            - os-viewer
            - os-explorer
            - os-admin
            - indigo
            - rdfbrowser
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
    os-viewer:   #image: openspending/os-viewer
        build: ./os-viewer
        expose:
          - "8000"
        ports:
          - "9003:8000"
        volumes:
            - ./os-viewer/dev_config:/app/app/config
        environment:
            - DEFAULT_HOST=http://localhost
            - DEFAULT_BASE_PATH=/viewer
            - OS_EXTERNAL_ADDRESS=http://localhost
            - OS_VIEWER_API_HOST=http://localhost
            - OS_VIEWER_AUTH_HOST=http://next.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://localhost
            - OS_VIEWER_DATAMINE_HOST=http://localhost
            #- OS_VIEWER_API_COSMO_HOST
            #- OS_VIEWER_BASE_PATH
    os-explorer:
        build: ./os-explorer
        volumes:
          - ./os-explorer/dev_themes:/app/app/scripts/services/themes
        expose:
          - "8000"
        environment:
          - WORKDIR=/apps
    os-admin:
        image: openspending/os-admin
        expose:
          - "8000"
        restart: always
    indigo:
        build: ./indigo
        ports:
          - "4200:4200"

#    vocol:
#        build: ./vocol
#        ports:
#          - "4200:4200"






# Subnet-Size net-Mask-Size (CIDR)
# 256 24
# 128 25
# 64 26
# 32 27
# 16 28 <<<<<
# 8 29
# 4 30
# 2 31
# 1 32

    #rudolf:

    #alignmentUI:

    #fileServerDataMining:







