version: '2'
services:
    linkedpipes:
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
        ports:
            - "8085:8085" # executor.webserver.port
            - "8080:8080" # Webserver & URI dereferencable URI for pipelines + templates
            - "8081:8081" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "3300:3300" # external.port.start port for external services like Fuseki
            - "9001:9001" # supervisord frontend
       # environment:
       #     - SUPERVISOR_USER=obeu
       #     - SUPERVISOR_PW=obeu
    triple_store_staging:
        build: ./fuseki
        volumes:
            - ../volumes/tripleStoreStaging/log:/usr/lib/fuseki/run/logs
            - ../volumes/tripleStoreStaging/data:/data
        ports:
            - "33030:3030"
    triple_store_production:
        build: ./fuseki
        volumes:
            - ../volumes/tripleStoreProduction/log:/usr/lib/fuseki/run/logs
            - ../volumes/tripleStoreProduction/data:/data
        ports:
            - "43030:3030"
    rudolf:
        build: ./rudolf
        volumes:
            - ../volumes/rudolf/log:/var/www/rudolf/storage/logs
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
        links:
            - linkedpipes
            - triple_store_staging
            - triple_store_production
            - rudolf
        ports:
            - "80:80"


    #rudolf:

    #alignmentUI:

    #fileServerDataMining:







