version: '2'
services:
    linkedpipes:
        build: ./linkedpipes
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
        ports:
            - "8085:8085" # executor.webserver.port
            - "8080:8080" # Webserver & URI dereferencable URI for pipelines + templates
            - "8081:8081" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data port
            - "3300:3300" # external.port.start port for external services like Fuseki
            - "9001:9001" # supervisord frontend
        links:
            - triple_store_staging
    triple_store_staging:
        build: ./fuseki
        volumes:
            - ../volumes/tripleStoreStaging/log:/var/log
            - ../volumes/tripleStoreStaging/data:/data
        ports:
            - "33030:3030"
            - "39001:9001" # supervisord frontend
    triple_store_production:
        build: ./fuseki
        volumes:
            - ../volumes/tripleStoreProduction/log:/var/log
            - ../volumes/tripleStoreProduction/data:/data
        ports:
            - "43030:3030"
            - "49001:9001" # supervisord frontend
    rudolf:
        build: ./rudolf
        volumes:
            - ../volumes/rudolf/log:/var/www/rudolf/storage/logs
        links:
            - triple_store_production
    nginx:
        build: ./nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
        links:
            - linkedpipes
            - triple_store_staging
            - triple_store_production
            - rudolf
            - os-viewer
        ports:
            - "80:80"
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
    os-viewer:
        image: openspending/os-viewer
        expose:
          - "8000"
        ports:
          - "9003:8000"
        environment:
            - WORKDIR=app
            - PORT=8000
            # For dev:
            - OS_EXTERNAL_ADDRESS=http://localhost
            - OS_VIEWER_API_HOST=http://localhost
            # For prod:
            #- OS_EXTERNAL_ADDRESS=http://eis-openbudgets.iais.fraunhofer.de
            #- OS_VIEWER_API_HOST=http://nginx:80
            - OS_VIEWER_AUTH_HOST=http://next.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://localhost


    #rudolf:

    #alignmentUI:

    #fileServerDataMining:







