version: '2'
services:
    alignmentmysql:
        build: ./alignmentmysql
        volumes:
            - ../volumes/alignment/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=alignment
            - MYSQL_ROOT_PASSWORD=$ALIGNMENT_MYSQL_PW
        ports:
            - "3306:3306"
    alignmentredis:
        build: ./alignmentredis
        volumes:
            - ../volumes/alignment/redis:/data
        ports:
            - "6379:6379"
    alignmentui:
        build: ./alignmentui
        volumes:
            - ../volumes/virtuosoStaging/data:/data
        environment:
            - MYSQL_ROOT_PASSWORD=$ALIGNMENT_MYSQL_PW
            - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
            - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
        links:
            - alignmentmysql
            - alignmentredis
    linkedpipes_fdp:
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes/data:/data
            - ../volumes/linkedpipes/log:/var/log
            - ./linkedpipes/configuration_update.properties:/etl/deploy/configuration.properties
        ports:
            - "8181:8181" # Webserver & URI dereferencable URI for pipelines + templates
            - "8170:8170" # executor-monitor.webserver.port
            - "2221:2221" # executor-monitor.ftp.port
            - "2223-2230:2223-2230" # Linked Pipes FTP data psort
            - "8101:9101" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    linkedpipes_1:
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes_1/data:/data
            - ../volumes/linkedpipes_1/log:/var/log
            - ./linkedpipes/configuration_update_1.properties:/etl/deploy/configuration.properties
        ports:
            - "8282:8282" # Webserver & URI dereferencable URI for pipelines + templates
            - "8270:8270" # executor-monitor.webserver.port
            - "8221:8221" # executor-monitor.ftp.port
            - "8223-8230:8223-8230" # Linked Pipes FTP data port
            - "8201:9201" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    linkedpipes_2:
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes_2/data:/data
            - ../volumes/linkedpipes_2/log:/var/log
            - ./linkedpipes/configuration_update_2.properties:/etl/deploy/configuration.properties
        ports:
            - "8383:8383" # Webserver & URI dereferencable URI for pipelines + templates
            - "8370:8370" # executor-monitor.webserver.port
            - "8321:8321" # executor-monitor.ftp.port
            - "8323-8330:8323-8330" # Linked Pipes FTP data port
            - "8301:9301" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    linkedpipes_3:
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes_3/data:/data
            - ../volumes/linkedpipes_3/log:/var/log
            - ./linkedpipes/configuration_update_3.properties:/etl/deploy/configuration.properties
        ports:
            - "8484:8484" # Webserver & URI dereferencable URI for pipelines + templates
            - "8470:8470" # executor-monitor.webserver.port
            - "8421:8421" # executor-monitor.ftp.port
            - "8423-8430:8423-8430" # Linked Pipes FTP data port
            - "8401:9401" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    linkedpipes_4:
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes_4/data:/data
            - ../volumes/linkedpipes_4/log:/var/log
            - ./linkedpipes/configuration_update_4.properties:/etl/deploy/configuration.properties
        ports:
            - "8585:8585" # Webserver & URI dereferencable URI for pipelines + templates
            - "8570:8570" # executor-monitor.webserver.port
            - "8521:8521" # executor-monitor.ftp.port
            - "8523-8530:8523-8530" # Linked Pipes FTP data port
            - "8501:9501" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    linkedpipes_5:
        build: ./linkedpipes
        restart: always
        volumes:
            - ../volumes/linkedpipes_5/data:/data
            - ../volumes/linkedpipes_5/log:/var/log
            - ./linkedpipes/configuration_update_5.properties:/etl/deploy/configuration.properties
        ports:
            - "8686:8686" # Webserver & URI dereferencable URI for pipelines + templates
            - "8670:8670" # executor-monitor.webserver.port
            - "8621:8621" # executor-monitor.ftp.port
            - "8623-8630:8623-8630" # Linked Pipes FTP data port
            - "8601:9601" # supervisord frontend
        links:
            - triple_store_staging
            - virtuoso_staging
            - sshserver
    sshserver:
        build: ./sshserver
        restart: always
        volumes:
            - ../volumes/nginx/dumps:/dumps
            - ../volumes/sshserver/log:/var/log
    virtuoso_staging:
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
            - ./virtuoso/staging/importDump.sh:/importDump.sh
            - ./virtuoso/staging/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
        environment:
            - DBA_PASSWORD=$VIRTUOSO_STAG_PW
            - SPARQL_UPDATE=true
            #- DEFAULT_GRAPH=
        ports:
            - "8890:8890"
            - "1111:1111"
    virtuoso_production:
        build: ./virtuoso
        restart: always
        volumes:
            - ../volumes/virtuosoProduction/data:/data
            - ../volumes/virtuosoStaging/data:/newdata
            - ./virtuoso/production/startVirtuoso.sh:/startVirtuoso.sh
            - ./virtuoso/production/supervisord.conf:/etc/supervisord.conf
            - ./virtuoso/production/virtuoso.ini:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini
        environment:
            - DBA_PASSWORD=$VIRTUOSO_PROD_PW
            - SPARQL_UPDATE=false
            #- DEFAULT_GRAPH=te
        ports:
            - "8891:8890"
            - "1112:1111"
    triple_store_staging:
        build: ./fuseki
        restart: always
        volumes:
            - ./fuseki/staging/start.sh:/start.sh
            - ./fuseki/staging/createGraphFiles.sh:/createGraphFiles.sh
            - ../volumes/tripleStoreStaging/log:/var/log
            - ../volumes/tripleStoreStaging/data:/data
            - ../volumes/nginx/dumps:/dumps
        ports:
            - "33030:3030"
            - "39001:9001" # supervisord frontend
    triple_store_production:
        build: ./fuseki
        restart: always
        volumes:
            - ./fuseki/production/start.sh:/start.sh
            - ../volumes/tripleStoreProduction/log:/var/log
            - ../volumes/tripleStoreProduction/data:/data
            - ../volumes/tripleStoreStaging/data:/newdata
        ports:
            - "43030:3030"
            - "49001:9001" # supervisord frontend
    rudolf:
        build: ./rudolf
        restart: always
        volumes:
            - ../volumes/rudolf/www:/var/www
        links:
            - triple_store_production
            - virtuoso_production
            - virtuoso_staging
    rdfbrowser:
        build: ./rdfbrowser
        volumes:
            - ../volumes/rdfbrowser/storage/database.sqlite:/var/www/RDFBrowser/storage/database.sqlite
            - ./rdfbrowser/dev/apache2.conf:/etc/apache2/apache2.conf
        ports:
            - "8111:80"
        links:
            - virtuoso_staging
            - virtuoso_production
    dam:
        build: ./dam
        #restart: always
        volumes:
            - ../volumes/dam/app:/DAM
        ports:
            - "5000:5000"
    nginx:
        build: ./nginx
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/nginx/letsencrypt/www:/tmp/letsencrypt/www # Lets encrypt files
            - ../volumes/nginx/letsencrypt/etc:/etc/letsencrypt # Lets encrypt files
            - ../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt # Lets encrypt files
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/images:/var/www/images
            - ./nginx/svg:/var/www/svg
        links:
            - linkedpipes_fdp
            - triple_store_staging
            - triple_store_production
            - virtuoso_staging
            - virtuoso_production
            - rudolf
            - os-viewer
            - os-explorer
            - os-admin
            - indigo
            - rdfbrowser
            - alignmentui
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
    os-viewer:   #image: openspending/os-viewer
        build: ./os-viewer
        expose:
          - "8000"
        ports:
          - "9003:8000"
        volumes:
            - ./os-viewer/prod_config:/app/app/config
        environment:
            - DEFAULT_HOST=http://eis-openbudgets.iais.fraunhofer.de
            - DEFAULT_BASE_PATH=/viewer
            - OS_EXTERNAL_ADDRESS=http://eis-openbudgets.iais.fraunhofer.de
            - OS_VIEWER_API_HOST=http://eis-openbudgets.iais.fraunhofer.de
            - OS_VIEWER_AUTH_HOST=http://next.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://eis-openbudgets.iais.fraunhofer.de
            - OS_VIEWER_DATAMINE_HOST=http://eis-openbudgets.iais.fraunhofer.de
            #- OS_VIEWER_API_COSMO_HOST
            #- OS_VIEWER_BASE_PATH
    os-explorer:
        build: ./os-explorer
        volumes:
          - ./os-explorer/prod_themes:/app/app/scripts/services/themes
        expose:
          - "8000"
        environment:
          - WORKDIR=/apps
    os-admin:
        image: openspending/os-admin
        expose:
          - "8000"
        restart: always
    indigo:
        build: ./indigo
        ports:
          - "4200:4200"

#    vocol:
#        build: ./vocol
#        ports:
#          - "4200:4200"






# Subnet-Size net-Mask-Size (CIDR)
# 256 24
# 128 25
# 64 26
# 32 27
# 16 28 <<<<<
# 8 29
# 4 30
# 2 31
# 1 32

    #rudolf:

    #alignmentUI:

    #fileServerDataMining:







