version: '2'
services:

    alignmentmysql:
        image: openbudgets/alignmentmysql
        build: ./alignmentmysql
        volumes:
            - ../volumes/alignment/mysql:/var/lib/mysql
        env_file:
            - ../.env
        ports:
            - "3306:3307"
    #alignmentredis:
    #    image: openbudgets/alignmentredis
    #    build: ./alignmentredis
    #    volumes:
    #        - ../volumes/alignment/redis:/data
    alignment:
        image: openbudgets/alignment
        build: ./alignment
        volumes:
            - ../volumes/virtuosoStaging/data:/data
            - ../volumes/alignment/composer:/root/.composer/cache
            #- ../volumes/alignment/storage:/var/www/alignment/storage
            #- ../volumes/alignment/stappler:/var/www/alignment/public/system
            #- ../volumes/alignment/bootstrap:/var/www/alignment/bootstrap
        env_file:
            - ../.env
        expose:
          - "80"
        ports:
            - "9559:80"
        links:
            - alignmentmysql

    nginx:
        image: openbudgets/nginx
        build: ./nginx
        restart: always
        volumes:
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ../volumes/nginx/log:/var/log/nginx
            - ../volumes/nginx/dumps:/var/www/dumps # serve rdf-file-dumps via http
            - ../volumes/nginx/letsencrypt/www:/tmp/letsencrypt/www # Lets encrypt files
            - ../volumes/nginx/letsencrypt/etc:/etc/letsencrypt # Lets encrypt files
            - ../volumes/nginx/letsencrypt/lib:/var/lib/letsencrypt # Lets encrypt files
            - ../volumes/linkedpipes:/var/www/linkedpipes # serve ftp-files of Linkedpipes via http
            - ./nginx/static_files/images:/var/www/images
            - ./nginx/static_files/svg:/var/www/svg
        links:
            - alignment
        ports:
            - "80:80" # http
            - "443:443" # https
            - "2222:2222" # Serve static files of Linked Pipes output via http as alternative to ftp
